apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort  # Use LoadBalancer or ClusterIP depending on your setup
  selector:
    app: fastapi-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
