apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.name" . }}
  namespace: {{include "api.namespaceName" .}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.labels" . | nindent 8 }}
    spec:
      containers:
      - name: fastapi-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: {{ include "api.name" . }}-env
        {{- if .Values.vault.enabled }}
        - secretRef:
            name: {{ include "api.name" . }}-secrets
        {{- end }}
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 60
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 60
