{{- if and .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.name" . }}-cert
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "api.name" . }}-cert
    creationPolicy: Orphan
  data:
  - secretKey: ca.crt
    remoteRef:
      key: global
      property: ca
{{- end }}