{{- if .Values.vault.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.name" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "api.name" . }}-secrets
    creationPolicy: Owner
  data:
{{- range $key, $value := .Values.vault.secrets }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $value.vaultKey }}
        property: {{ $value.property }}
{{- end }}
{{- end }}