{{- if and .Values.vault.enabled .Values.vault.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "api.name" . }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.vault.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ include "api.name" . }}-secrets
    creationPolicy: Orphan
  data:
  {{- with .Values.vault.secrets }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}