apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
  namespace: {{include "api.namespaceName" .}}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "api.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.service.portName }}
