apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
  namespace: {{include "api.namespaceName" .}}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "api.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    name: http
