apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-api.name" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dns-api.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
