releasename: testapi
replicaCount: 1

image:
  repository: dns-api
  tag: "7.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  portName: http

servicemonitor:
  enabled: true
  interval: 30s
  release: my-prometheus-operator

