releasename: testapi
replicaCount: 1

image:
  repository: dns-api
  tag: "7.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  portName: http

servicemonitor:
  enabled: true
  interval: 30s
  release: my-prometheus-operator

env:
  VAR_ONE: "value1"
  VAR_TWO: "value2"
  VAR_THREE: "value3"

vault:
  enabled: true
  clusterSecretStore: vault-cluster-secret-store

  secrets:
    AWX_TOKEN:
      vaultKey: ds
      property: awx_token

